services:
  frontend:
    image: budcoded/productmanagementsystemui:latest
    ports:
      - "3000:3000"
  backend:
    image: budcoded/productmanagementsystem:latest
    ports:
      - "1111:1111"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - IP = 172.16.128.197
      - PORT = 3308
      - MYSQL_ROOT_PASSWORD = password
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.6
  db:
    image: mysql
    healthcheck:
      test: ["CMD", "ls"]
    ports:
      - "3308:3306"
    volumes:
      - productmanagementsystem:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = password
volumes:
  productmanagementsystem: